### ISSUE TITLE
Request to make output of empty ls command to be more friendly and usefull

### ISSUE THREAD

**Issue by flightman69** [theredditbandit/pman#10]
The current output of "pman ls" which has currently 0 projects
![image](https://github.com/theredditbandit/pman/assets/89738046/c620a5f5-2130-44a3-866e-d6f85785ab6c)

**Comment by theredditbandit** [comment]
alright , im not going to print the empty table. Instead will just say there's nothing in the database and that's because no projects are indexed.

**Comment by theredditbandit** [comment]
![image](https://github.com/theredditbandit/pman/assets/85390033/fd3f459b-0e12-4b4a-af7a-2714c0417d41)
This is what you get now
