### ISSUE TITLE
Lack of tests

### ISSUE THREAD

**Issue by ccoVeille** [theredditbandit/pman#16]
Hi @theredditbandit 

I see a major issue with your tool. Its maintenance.

The code is not tested.

While your tool is great, it can't be maintained easily. Anyone contributing to your tool via PR may break something and it won't be noticed until merged by someone else.

**Comment by theredditbandit** [comment]
Hi , thanks for raising this issue.

You're absolutely right , having a robust test suite is crucial for maintainability especially as more contributors get involved.

When I was initially writing this tool , I only ever saw myself using this and I didn't feel like investing the time and effort to write tests and have proper coverage. 

I will be adding tests sometime in the future but I'm not familiar with testing in go so it will take a while. 
In the meantime if you want to add tests yourself via a PR , I'd be more than happy to review and merge them.

**Comment by ccoVeille** [comment]
Sure.

Just for you to get used to my sense of humor. Your message sounds somehow like "I know my room is a mess, but you can help me to tidy up, sure" 😅😂

**Comment by ccoVeille** [comment]
> Hi , thanks for raising this issue.
> 
> You're absolutely right , having a robust test suite is crucial for maintainability especially as more contributors get involved.
> 
> When I was initially writing this tool , I only ever saw myself using this and I didn't feel like investing the time and effort to write tests and have proper coverage. 
> 
> I will be adding tests sometime in the future but I'm not familiar with testing in go so it will take a while. 
> In the meantime if you want to add tests yourself via a PR , I'd be more than happy to review and merge them.

A more serious reply now. Tests are important for detecting regressions. Using tests also forces you to write code that can be tested, which lead to empower yourself in writing better code.

**Comment by theredditbandit** [comment]
> Sure.
> 
> Just for you to get used to my sense of humor. Your message sounds somehow like "I know my room is a mess, but you can help me to tidy up, sure" 😅😂

haha yeah and thank you 😂

**Comment by yannick2009** [comment]
lemme try to add these tests !

**Comment by ccoVeille** [comment]
Thanks @yannick2009 you did it, and you did it in the middle of me adding CI, so you had to fix more that you were initially supposed to
