### ISSUE TITLE
Add CI and GitHub actions

### ISSUE THREAD

**Issue by ccoVeille** [theredditbandit/pman#24]
I'm thinking about launching the tests, when they will be added, but also adding golangci-lint check.

**Comment by ccoVeille** [comment]
The CI should be added before #23 get merged because code quality should be enforced before refactoring.

**Comment by ccoVeille** [comment]
I can do it of course

**Comment by ccoVeille** [comment]
I did :smile:

**Comment by theredditbandit** [comment]
Thanks a lot for adding CI , I merged all the PRs and GHA is working as expected without any extra configuration , I already have 3 PR's from dependabot for version updates

**Comment by ccoVeille** [comment]
My pleasure
