### ISSUE TITLE
Is there a command to CD into the indexed project or via interactive mode?

### ISSUE THREAD

**Issue by lavantien** [theredditbandit/pman#52]
If it's currently not supported, is it out of scope for pman's features? And any plan for adding this use case?

**Comment by theredditbandit** [comment]
I'm actually working on adding a cd command right now, it is fully in scope of pman's features and should be added within this week

**Comment by theredditbandit** [comment]
After much consideration I have decide not to add the `cd` functionality to pman as this is better left to tools like [zoxide](https://github.com/ajeetdsouza/zoxide) and [zsh z](https://github.com/agkozak/zsh-z) as they do this much better than I can implement it in pman.
