### ISSUE TITLE
Key not found in db error

### ISSUE THREAD

**Issue by TypicalAM** [theredditbandit/pman#60]
Hi, thanks for creating the project! I was looking for exactly that and when testing it seems like I found a bug. Here is a gif of the encountered behaviour:

![man-pr](https://github.com/theredditbandit/pman/assets/50233321/55ac736e-c827-46e2-bdc2-b6be05a6174f) 

After adding two projects `pman ls` fails with `Error: key not found in db`.

**Comment by theredditbandit** [comment]
Hmm , that is weird. could you share the version of pman you're. 

you can get the version by `pman -v` , the latest is v1.1.0
![image](https://github.com/theredditbandit/pman/assets/85390033/f30dc6b0-66ad-4a59-aa75-a4ca1ce16994)

**Comment by theredditbandit** [comment]
never mind , I managed to recreate it on my machine with the latest version.  

will update as soon as I have narrowed down the issue/released a fix.

Thanks again for catching this , I completely missed it while testing.

**Comment by theredditbandit** [comment]
Hi there! , 

sorry it took this long but the issue is fixed now!
