### ISSUE TITLE
add support for readme.md files with non uniform capitalization 

### ISSUE THREAD

**Issue by theredditbandit** [theredditbandit/pman#63]
The code was already there, but I would like you to suggest trying multiple names (yes, it would need a refactoring)

Some projects have:
- README.md
- Readme.md
- readme.md
- ReadMe.md
- … all the above without a .md

_Originally posted by @ccoVeille in https://github.com/theredditbandit/pman/pull/62#discussion_r1662297437_

**Comment by ccoVeille** [comment]
The variety is impressive

https://github.com/search?q=path%3A%2Freadme*+-path%3Areadme.md&type=code

.txt
.markdown
.text
.TXT
.Text
.rst (this one is restructuredText format)
.Markdown

You should consider a case insensitive glob of files starting with readme

**Comment by theredditbandit** [comment]
great idea , thanks
