### ISSUE TITLE
Wrong alias description when using `pman alias`

### ISSUE THREAD

**Issue by TypicalAM** [theredditbandit/pman#71]
Hi! When using `pman alias`, followed by `pman ls` the project name bugs out, see below gif:

![man-pr](https://github.com/user-attachments/assets/1f4c5cf6-683a-4623-8a9e-88f14616642a)

`pman version 1.1.0`

**Comment by theredditbandit** [comment]
Hi! , Nice catch. I think this might be some left over debug print statements causing this issue. I'll push a fix asap

**Comment by theredditbandit** [comment]
Hi there @TypicalAM! , 

I've published v1.1.1 that should address this issue , can you take a look.
